# ----
# Site

title: Ruby on Rails Cheatsheet
url: 'https://deepakmahakale.com/ruby-on-rails-cheatsheet/'
baseurl: '/ruby-on-rails-cheatsheet'
google_measurement_id: G-Z571RZ46QW
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The Ultimate Ruby on Rails Cheatsheet.
author:
  name: Deepak Mahakale
  email: hello@deepakmahakale.in
  twitter: deepakmahakale
social:
  name: Github
  links:
    - https://github.com/deepakmahakale

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:

jekyll-archives:
  enabled: ['categories']

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      type: 'posts'
    values:
      layout: 'post'
      comments: true
  - scope:
      type: 'sets'
    values:
      _hide_content: true
  - scope:
      path: 'index.html'
    values:
      body_class: 'show_hero_search'

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
